# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WishListApp', '0002_auto_20151230_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kadouser',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
