# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WishListApp', '0003_auto_20160113_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='name',
            new_name='item_title',
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='descripton',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='store',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
