# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WishListApp', '0004_auto_20160224_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='item_title',
            new_name='name',
        ),
    ]
