# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 18:00
from __future__ import unicode_literals

import WishListApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WishListApp', '0005_auto_20160224_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kadouser',
            name='photo',
        ),
        migrations.AddField(
            model_name='kadouser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=WishListApp.models.upload_avatar_to),
        ),
    ]
