# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-16 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WishListApp', '0007_auto_20160609_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='name',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='quantity',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
